name: angel
version: '0.6.3'
synopsis: Process management and supervision daemon
description: ! '@angel@ is a daemon that runs and monitors other processes.  It

  is similar to djb''s `daemontools` or the Ruby project `god`.


  It''s goals are to keep a set of services running, and to facilitate

  the easy configuration and restart of those services.

  See the homepage for documentation.'
category: System
author: Jamie Turner
maintainer: Michael Xavier <michael@michaelxavier.net>
license: BSD3
github: MichaelXavier/Angel.git
homepage: http://github.com/MichaelXavier/Angel
bug-reports: http://github.com/MichaelXavier/Angel/issues
extra-source-files:
- README.md
- changelog.md
- test/test_jobs/CompliantJob.hs
- test/test_jobs/StubbornJob.hs
dependencies:
  - base
  - process
  - time
  - optparse-applicative
  - mtl
  - configurator 
  - stm 
  - containers 
  - unordered-containers 
  - unix 
  - old-locale
  - text 
  - transformers

library:
  source-dirs: src
  exposed-modules:
    - Angel.Config
    - Angel.Data
    - Angel.Job
    - Angel.Prelude
    - Angel.Log
    - Angel.Util
    - Angel.Files

executables:
  angel:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded
    dependencies:
    - angel

tests:
  spec:
    main: Spec.hs
    source-dirs:
    - src
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - process
    - time
stability: Stable
